DDCE-5125 Play 3.0 Migration
hmrc/merchandise-in-baggage pull request #139
Opened 2024-03-21 12:42 UTC by mywyau

2024-03-28 13:52 UTC, gastonracui commented on project/AppDependencies.scala
> +    "com.beachape"          %% "enumeratum-play"           % "1.8.0" //versions 1.7.1+ are not binary compatible with previous ones
remove the comment

2024-03-28 18:48 UTC, gastonracui requested changes

2024-04-03 10:23 UTC, mywyau commented on project/CodeCoverageSettings.scala
> +      coverageMinimumStmtTotal := 90,
jenkins pr builder is saying coverage is at ~91% going to change to 91 for now.

2024-04-03 10:36 UTC, gastonracui approved these changes

2024-04-03 11:10 UTC, merged